#' ---
#' title: IL data formatting
#' output:
#'   html_document:
#'     theme: paper
#'     toc: true
#'     toc_float: true
#' ---

#' # Session infomation

sessionInfo()

#' # Load library

# Load library
output <- sapply(c("MN", "WI", "IA","IL"), function(x) paste0(x, ".dat.latest") )
rm(list = ls(all.names=T)[!(ls(all.names=T) %in% output)] ) # clear all data
library(tidyverse)
source("suppl01_sp-removal.R")

#' # Read data
#' **NOTE: use `readr::read_csv()` instead of `read.csv()` to read data - `read.csv()` treated blanks weiredly in this dataset**
#' 
#' - `01_data/data-org_il-fish.csv` - fish data
#' - `01_data/data-org_il_station.csv` - site date
#' - `01_data/data-org_il_visit.csv` - visit data
#+ message = FALSE, warning = FALSE

# Read data ---------------------------------------------------------------
IL.dat_fish <- read_csv("./data_raw_fish/data-org_il-fish.csv")
IL.dat_site <- read_csv("./data_raw_fish/data-org_il-station.csv")
IL.dat_visit <- read_csv("./data_raw_fish/data-org_il-visit.csv")

#' # Fish data formatting
#' Remove unidentified or hybrid species. These are identified if `Name2` is either `NA`, `hybrid` or `larvae`

# Fish data formatting ----------------------------------------------------


## format Common_Name
## replace space with underscore
## rename to upppercases
## remove '_(AMMOCOETE)' from string
## replace 'NORTHERN_HOG_SUCKER' with 'NORTHERN_HOGSUCKER'
## replace 'TROUT-PERCH' and 'TROUTPERCH' with 'TROUT_PERCH'
## drop unidentified
## drop hybrid and larval species
## remove GOLDFISH and PEARL DACE

 IL.dat_fish %>%
  mutate(Common_Name = str_replace_all(Common_Name, pattern = "\\s", replacement = "_") ) %>%
  mutate(Common_Name = str_to_upper(Common_Name) ) %>%
  mutate(Common_Name = str_replace(Common_Name, "NORTHERN_HOG_SUCKER", "NORTHERN_HOGSUCKER")) %>%
  filter(!(Common_Name %in% sp_rm) ) -> IL.dat_fish # remove hybrid and unidentified species using sp_rm list

## check difference from Kim's script - why pearl dace removed?
## one observation fewer than Kim's original file
print(unique(IL.dat_fish$Common_Name[IL.dat_fish$Common_Name %in% sp_rm]) )

#' # Merge datasets
#' Merge `IL.dat_fish`, `IL.dat_visit` and `IL.dat_site`
#' 
#' - `IL.dat_fish` as a base dataset because it includes fish data
#' - `IL.dat_visit` is joined to obtain sampling date
#' - `IL.dat_site` is joined to obtain GPS location (Lat and Lon)

# (1) Add visit and station data to fish data ---------------------------------

 IL.dat = IL.dat_fish %>%
  drop_na(FishSampleID_IDNR) %>% # drop NA FishSampleID_IDNR (unique visit ID)
  select(c(FishSampleID_IDNR, Common_Name, CountOfIndividuals)) %>% # select columns
  group_by(FishSampleID_IDNR, Common_Name) %>% 
  summarise(Abundance = sum(CountOfIndividuals)) %>% # calculate the abundance of each species based on SiteSeqNo (VisitID)
  left_join(IL.dat_visit, by = "FishSampleID_IDNR") %>% # merge Visit data
  filter (!duplicated(cbind(FishSampleID_IDNR, Common_Name))) %>% # remove duplicate generated by left_join
  left_join(IL.dat_site, by = "StationCode") %>% # merge site data
  drop_na(Abundance) %>% # drop NA, which does not have SiteID
  mutate(State = "IL") %>% # add State column
  select(c(State, StationCode, FishSampleID_IDNR, CollectionDate, Latitude_DDeg, Longitude_DDeg, Common_Name, Abundance) ) %>% # select columns
  rename(SiteID = StationCode, VisitID = FishSampleID_IDNR, Species = Common_Name, Lat = Latitude_DDeg, Lon = Longitude_DDeg, Date = CollectionDate) # rename columns
  IL.dat$SiteID <- paste0("IL_", as.character(IL.dat$SiteID)) # attach State code in SiteID

  length(unique(IL.dat$VisitID) ) # n = 1577
  length(unique(IL.dat$SiteID) ) # n = 1061

  # see the final data including all sampling occasion
  IL.dat # n= 32276

# (2) Select the most recent sampling occasion by SiteID ---------------------------
IL.dat.latest = IL.dat %>% 
  select(c(SiteID, VisitID, Date)) %>%
  group_by(SiteID) %>%
  slice(which.max(as.Date(Date, '%m/%d/%Y'))) %>% # select the most recent sampling occasion based on date
  right_join(IL.dat, by = "VisitID") %>% # merge the original data (right_join)
  drop_na(SiteID.x) %>% # drop NA SiteID
  group_by(SiteID.x) %>% 
  filter (!duplicated(Species)) %>% # remove duplicate automatically generated by filtering the recent sampling
  select(c(State, SiteID.x, VisitID, Date.x, Lat, Lon, Species, Abundance)) %>% # select columns
  rename(SiteID = SiteID.x, VisitID = VisitID, Date = Date.x) # change column name


#' # Final data 
 # Final data only included the latest sampling occasion
 IL.dat.latest # row number = 20835
 n_distinct(IL.dat.latest$SiteID) # n = 1061 correct
 n_distinct(IL.dat.latest$VisitID) # n = 1061 correct

 # Export final data into data_output folder 
 filename <- paste0("./data_outcome/fishdata_il_latest", Sys.Date(), ".csv")
 write.csv(IL.dat.latest, filename)
