#' ---
#' title: MN data formatting
#' output:
#'   html_document:
#'     theme: paper
#'     toc: true
#'     toc_float: true
#' ---

#' # Session infomation

sessionInfo()

#' # Load library

  # Load library
  output <- sapply(c("MN", "WI", "IA","IL"), function(x) paste0(x, ".dat.latest") )
  rm(list = ls(all.names=T)[!(ls(all.names=T) %in% output)] ) # clear all data
  library(tidyverse)
  source("suppl01_sp-removal.R")
  
#' # Read data
#' **NOTE: use `readr::read_csv()` instead of `read.csv()` to read data - `read.csv()` treated blanks weiredly in this dataset**
#' 
#' - `01_data/data-org_mn_fish.csv` - fish data
#' - `01_data/data-org_mn_station.csv` - site date
#' - `01_data/data-org_mn_visit.csv` - visit data
#+ message = FALSE, warning = FALSE

  # Read data ---------------------------------------------------------------
  MN.dat_fish <- read_csv("./data_raw_fish/data-org_mn-fish.csv") %>% mutate(FieldNum = str_to_upper(FieldNum) )
  MN.dat_site <- read_csv("./data_raw_fish/data-org_mn-station.csv") %>% mutate(FieldNum = str_to_upper(FieldNum) )
  MN.dat_visit <- read_csv("./data_raw_fish/data-org_mn-visit.csv") %>% mutate(FieldNum = str_to_upper(FieldNum) )
  
#' # Fish data formatting
#' Remove unidentified or hybrid species. These are identified if `Name2` is either `NA`, `hybrid` or `larvae`

  # Fish data formatting ----------------------------------------------------
  ## Check unidentified or hybrid species
  unique(MN.dat_fish$CommonName[is.na(MN.dat_fish$Name2)])
  unique(MN.dat_fish$CommonName[MN.dat_fish$Name2 %in% c("hybrid", "larvae")])
  
  ## format CommonName
  ## replace space with underscore
  ## rename to upppercases
  ## remove '_(AMMOCOETE)' from string
  ## replace 'NORTHERN_HOG_SUCKER' with 'NORTHERN_HOGSUCKER'
  ## replace 'TROUT-PERCH' and 'TROUTPERCH' with 'TROUT_PERCH'
  ## drop unidentified
  ## drop hybrid and larval species
  ## remove GOLDFISH and PEARL DACE
  
  MN.dat_fish %>%
    mutate(CommonName = str_replace_all(CommonName, pattern = "\\s", replacement = "_") ) %>%
    mutate(CommonName = str_to_upper(CommonName) ) %>%
    mutate(CommonName = str_remove(CommonName, "_\\(AMMOCOETE\\)")) %>% # remove '_(AMMOCOETE)' from string
    mutate(CommonName = str_replace(CommonName, "NORTHERN_HOG_SUCKER", "NORTHERN_HOGSUCKER")) %>%
    mutate(CommonName = str_replace(CommonName, "TROUT-PERCH", "TROUT_PERCH")) %>%
    mutate(CommonName = str_replace(CommonName, "TROUTPERCH", "TROUT_PERCH")) %>%
    drop_na(Name2) %>% # remove NA
    filter(!(Name2 %in% c("hybrid", "larvae")) ) %>% 
    filter(!(CommonName %in% sp_rm) ) -> MN.dat_fish 

  
  ## check difference from Kim's script - why pearl dace removed?
  ## one observation fewer than Kim's original file
  print(unique(MN.dat_fish$CommonName[MN.dat_fish$CommonName %in% sp_rm]) )

#' # Merge datasets
#' Merge `MN.dat_fish`, `MN.dat_visit` and `MN.dat_site`
#' 
#' - `MN.dat_fish` as a base dataset because it includes fish data
#' - `MN.dat_visit` is joined to obtain sampling date
#' - `MN.dat_site` is joined to obtain GPS location (Lat and Lon)

  # (1) Add visit and station data to fish data ---------------------------------
  MN.dat = MN.dat_fish %>%
    left_join(MN.dat_visit, by = "VisitNum") %>% # merge Visit data
    rename(FieldNum = FieldNum.x) %>% # rename FieldNum (derive from fish_dat)
    left_join(MN.dat_site, by = "FieldNum") %>% # merge site information
    drop_na(FieldNum.y) %>% # drop NA FieldNum in dat_visit
    mutate(State = "MN") %>% # add State column
    select(c(State, FieldNum, VisitNum, VisitDate, LAT8xDD, LON8xDD, Name1, Name2, CommonName, Number) ) %>% # select columns
    rename(SiteID = FieldNum, VisitID =VisitNum, Genus = Name1, Species = Name2, Abundance = Number, Lat = LAT8xDD, Lon = LON8xDD, Date = VisitDate) # rename columns
    MN.dat$SiteID <- paste0("MN_", as.character(MN.dat$SiteID)) # attach State code in SiteID
  
  length(unique(MN.dat$VisitID) ) # n = 3049
  length(unique(MN.dat$SiteID) ) # n = 2372
  
  # see the final data including all sampling occasion
  MN.dat

  
  # (2) Select the most recent sampling occasion by SiteID ---------------------------
  MN.dat.latest = MN.dat %>% 
    select(c(SiteID, VisitID, Date)) %>%
    group_by(SiteID) %>%
    slice(which.max(as.Date(Date, '%m/%d/%Y'))) %>% # select the most recent sampling occasion based on date
    right_join(MN.dat, by = "VisitID") %>% # merge the original data (right_join)
    drop_na(SiteID.x) %>% # drop NA SiteID
    group_by(SiteID.x) %>% 
    filter (!duplicated(CommonName)) %>% # remove duplicate automatically generated by filtering the recent sampling
    select(c(State, SiteID.x, VisitID, Date.x, Lat, Lon, CommonName, Abundance)) %>% # select columns
    rename(SiteID = SiteID.x, VisitID = VisitID, Date = Date.x, Species = CommonName) # change column name

  
#' # Final data 
 # Final data only included the latest sampling occasion
  MN.dat.latest # row number = 30,275 correct
  n_distinct(MN.dat.latest$SiteID) # n = 2372 correct
  n_distinct(MN.dat.latest$VisitID) # n = 2372 correct

 # Export final data into data_output folder
  filename <- paste0("./data_outcome/fishdata_mn_latest", Sys.Date(), ".csv")
  write.csv(MN.dat.latest, filename)  
  